### ISSUE TITLE
youtube error 153

### ISSUE THREAD

**Issue by sroggatz1977** [anyproto/anytype-ts#1743]
### Have you read a contributing guide?

- [x] I have read CONTRIBUTING.md
- [x] I have searched the existing issues and didn't find any that were similar
- [x] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

If I want to embed a youtube video via the link I get a error page from youtube displaying error 153. 
Any idea how to fix this?

### Expected Behavior

Show the video and play it.

### Steps To Reproduce

-

### Environment

```markdown
- OS: macOS 26.0.1
- Version: 0.50.5
```

**Comment by ra3orblade** [comment]
Hello, this is already fixed by the community contribution, you have 2 options:
- remove cookies for youtube in devtools: Debug -> Devtools -> 

<img width="1627" height="1070" alt="Image" src="https://github.com/user-attachments/assets/56eebbcd-9f82-42d7-ba38-050d17e9483c" />

- or download latest alpha version and use it until we made next public release.

**Comment by sroggatz1977** [comment]
![Image](https://github.com/user-attachments/assets/3fb35ae8-f753-44b5-ae73-93c2b2a89e28)

No cookies or better I hit clear but youtube is still showing 153 error.

**Comment by ra3orblade** [comment]
> ![Image](https://github.com/user-attachments/assets/3fb35ae8-f753-44b5-ae73-93c2b2a89e28)
> 
> No cookies or better I hit clear but youtube is still showing 153 error.

you should clear youtube cookies, not file://, check next folder

**Comment by sroggatz1977** [comment]
![Image](https://github.com/user-attachments/assets/0d8c0c3e-2e1b-48b5-a302-f7ba95352223)

I did of course. Still no effect.

**Comment by ra3orblade** [comment]
Download latest alpha then, users with this problem cleared Youtube cookies and it helped, its some Youtube embed protection logic.

**Comment by ra3orblade** [comment]
I've double checked and the problem actually persists.

**Comment by ra3orblade** [comment]
Marking as completed.
